sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gupta91sunil/docker-react -f Dockerfile.dev . 
  
script:
  - docker run -e CI=true gupta91sunil/docker-react npm run test -- --coverage

deploy:
  provider: elasticsbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-409102638378"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"